import type { Express } from "express";
import type { Server } from "http";
import publicMarketingRoutes from "./publicMarketing";
import authRoutes from "./auth";
import usersRoutes from "./users";
import kycRoutes from "./kyc";
import approvalsRoutes from "./approvals";
import dashboardRoutes from "./dashboard";
import transactionsRoutes from "./transactions";
import batchesRoutes from "./batches";
import advancesRoutes from "./advances";
import investmentsRoutes from "./investments";
import templatesRoutes from "./templates";
import recurringRoutes from "./recurringPayments";
import paymentLinksRoutes from "./paymentLinks";
import topupsRoutes from "./topups";
import quickPayRoutes from "./quickPay";
import seedRoutes from "./seed";

/** Demo seed is for local/dev. In production it is off unless ENABLE_SEED_API=1 (e.g. a dedicated staging sandbox). */
function isSeedApiEnabled(): boolean {
  if (process.env.NODE_ENV !== "production") return true;
  const v = process.env.ENABLE_SEED_API?.trim().toLowerCase();
  return v === "1" || v === "true" || v === "yes" || v === "on";
}
import adminRoutes from "./admin";
import mpesaRoutes from "./mpesa";
import notificationsRoutes from "./notifications";
import impersonationRoutes from "./impersonation";
import overdraftRoutes from "./overdraft";
import auditorRoutes from "./auditor";
import subscriptionRoutes from "./subscriptions";
import supportRoutes from "./support";
import paymentSettingsRoutes from "./paymentSettings";
import hrRoutes from "./hr";
import hrPublicRoutes from "./hrPublic";
import leavePoliciesRoutes from "./leavePolicies";
import leaveBalancesRoutes from "./leaveBalances";
import compulsoryLeaveRoutes from "./compulsoryLeave";
import overtimePoliciesRoutes from "./overtimePolicies";
import leaveLogsRoutes from "./leaveLogs";
import reportsRoutes from "./reports";
import employeeWalletRoutes from "./employeeWallets";
import assetRegistryEventsRoutes from "./assetRegistryEvents";
import peopleRoutes from "./people";
import arRoutes from "./ar";
import businessRoutes from "./business";
import centyPosRoutes from "./centyPos";
import centypackHubRoutes from "./centypackHub";
import centypackFarmersRoutes from "./centypackFarmers";
import centypackCropsRoutes from "./centypackCrops";
import centypackVarietiesRoutes from "./centypackVarieties";
import centypackCartonTypesRoutes from "./centypackCartonTypes";
import centypackWorkerCategoriesRoutes from "./centypackWorkerCategories";
import centypackWarehousesRoutes from "./centypackWarehouses";
import centypackGradeCodesRoutes from "./centypackGradeCodes";
import centypackDefectTypesRoutes from "./centypackDefectTypes";
import centypackIntakeRoutes from "./centypackIntake";
import centypackGdnsRoutes from "./centypackGdns";
import centypackGradingSessionsRoutes from "./centypackGradingSessions";
import centypackPackSessionsRoutes from "./centypackPackSessions";
import centypackLabourersRoutes from "./centypackLabourers";
import centypackLabourAttendanceRoutes from "./centypackLabourAttendance";
import centypackLaborRoutes from "./centypackLabor";
import centypackStockRoutes from "./centypackStock";

export async function registerRoutes(httpServer: Server, app: Express): Promise<Server> {
  app.use(publicMarketingRoutes);
  app.use(authRoutes);
  app.use(usersRoutes);
  app.use(impersonationRoutes);
  app.use(kycRoutes);
  app.use(approvalsRoutes);
  app.use(businessRoutes);
  app.use(dashboardRoutes);
  app.use(transactionsRoutes);
  app.use(batchesRoutes);
  app.use(advancesRoutes);
  app.use(investmentsRoutes);
  app.use(templatesRoutes);
  app.use(recurringRoutes);
  app.use(paymentLinksRoutes);
  app.use(topupsRoutes);
  app.use(quickPayRoutes);
  if (isSeedApiEnabled()) {
    app.use(seedRoutes);
  }
  app.use(adminRoutes);
  app.use(mpesaRoutes);
  app.use(notificationsRoutes);
  app.use(overdraftRoutes);
  app.use(auditorRoutes);
  app.use(subscriptionRoutes);
  app.use(supportRoutes);
  app.use(paymentSettingsRoutes);
  app.use(leavePoliciesRoutes);
  app.use(leaveBalancesRoutes);
  app.use(compulsoryLeaveRoutes);
  app.use(overtimePoliciesRoutes);
  app.use(leaveLogsRoutes);
  app.use("/api/hr", hrRoutes);
  app.use("/api/hr-public", hrPublicRoutes);
  app.use(peopleRoutes);
  app.use(reportsRoutes);
  app.use(arRoutes);
  app.use(employeeWalletRoutes);
  app.use(assetRegistryEventsRoutes);
  app.use(centyPosRoutes);
  app.use(centypackHubRoutes);
  app.use(centypackFarmersRoutes);
  app.use(centypackCropsRoutes);
  app.use(centypackVarietiesRoutes);
  app.use(centypackCartonTypesRoutes);
  app.use(centypackWorkerCategoriesRoutes);
  app.use(centypackWarehousesRoutes);
  app.use(centypackGradeCodesRoutes);
  app.use(centypackDefectTypesRoutes);
  app.use(centypackIntakeRoutes);
  app.use(centypackGdnsRoutes);
  app.use(centypackGradingSessionsRoutes);
  app.use(centypackPackSessionsRoutes);
  app.use(centypackLabourersRoutes);
  app.use(centypackLabourAttendanceRoutes);
  app.use(centypackLaborRoutes);
  app.use(centypackStockRoutes);

  return httpServer;
}
